<script setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import { Link } from '@inertiajs/vue3';
const props = defineProps({ resumo: Object, top_produtos_hoje: Array, vendas_bar_por_ponto: Array, caixas_por_ponto: Array });
const euros = (v) => Number(v ?? 0).toFixed(2) + '€';
const hoje = new Date().toLocaleDateString('pt-PT');
</script>
<template><AppLayout><div class="mb-6 flex items-center justify-between"><h1 class="text-2xl font-black">Relatórios</h1><Link :href="route('relatorios.periodo')" class="rounded-md bg-slate-900 px-4 py-2 font-bold text-white">Relatório por período</Link></div><h2 class="mb-4 font-black">HOJE — {{ hoje }}</h2><div class="grid gap-4 md:grid-cols-4"><div v-for="card in [['Total Vendido', resumo.total_vendas_hoje], ['Nº Pedidos', resumo.total_pedidos_hoje], ['Média/Pedido', resumo.media_por_pedido], ['Doações', resumo.doacoes_hoje]]" :key="card[0]" class="rounded-lg bg-white p-5 shadow-sm"><div class="text-sm text-slate-500">{{ card[0] }}</div><div class="mt-2 text-3xl font-black">{{ card[0] === 'Nº Pedidos' ? card[1] : euros(card[1]) }}</div></div></div><div class="mt-4 grid gap-4 md:grid-cols-3"><div class="rounded-lg bg-white p-5 shadow-sm">Restaurante <strong class="float-right">{{ euros(resumo.vendas_restaurante_hoje) }}</strong></div><div class="rounded-lg bg-white p-5 shadow-sm">Bar Conta <strong class="float-right">{{ euros(resumo.vendas_bar_hoje) }}</strong></div><div class="rounded-lg bg-white p-5 shadow-sm">Bar Pré-pago <strong class="float-right">{{ euros(resumo.vendas_prepago_hoje) }}</strong></div></div><section class="mt-6 rounded-lg bg-white p-5 shadow-sm"><h2 class="mb-3 font-black">Dinheiro do Bar por ponto</h2><div v-if="!vendas_bar_por_ponto?.length" class="text-sm text-slate-500">Sem vendas de bar neste período.</div><div v-for="linha in vendas_bar_por_ponto" :key="linha.ponto" class="flex justify-between border-t py-2"><span class="font-bold">{{ linha.ponto }}</span><strong>{{ euros(linha.total) }} · {{ linha.pedidos }} pedidos</strong></div></section><section class="mt-6 rounded-lg bg-white p-5 shadow-sm"><h2 class="mb-3 font-black">Caixa e fundo de maneio</h2><div v-if="!caixas_por_ponto?.length" class="text-sm text-slate-500">Ainda não há caixas abertas.</div><div v-for="linha in caixas_por_ponto" :key="linha.ponto" class="grid gap-2 border-t py-3 text-sm md:grid-cols-6"><strong>{{ linha.ponto }}</strong><span>Fundo: {{ euros(linha.fundo_maneio) }}</span><span>Vendas: {{ euros(linha.vendas) }}</span><strong class="text-emerald-700">Esperado: {{ euros(linha.esperado_caixa) }}</strong><span>Contado: {{ euros(linha.valor_contado) }}</span><strong>Dif.: {{ euros(linha.diferenca) }}</strong></div></section><section class="mt-6 rounded-lg bg-white p-5 shadow-sm"><h2 class="mb-3 font-black">Top 5 Produtos Hoje</h2><table class="w-full text-left text-sm"><tbody><tr v-for="p in top_produtos_hoje" :key="p.nome" class="border-t"><td class="py-2 font-bold">{{ p.nome }}</td><td>{{ p.quantidade }}</td><td class="text-right">{{ euros(p.total) }}</td></tr></tbody></table></section></AppLayout></template>

